# Generated by Django 3.2.7 on 2021-12-06 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('q_option1', models.CharField(max_length=100)),
                ('q_option2', models.CharField(max_length=100)),
                ('q_option3', models.CharField(max_length=100)),
                ('q_option4', models.CharField(max_length=100)),
                ('q_ans', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reasoning',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=850)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_cresult', models.IntegerField()),
                ('user_wresult', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Self_development',
            fields=[
                ('self_qid', models.AutoField(primary_key=True, serialize=False)),
                ('self_question', models.CharField(max_length=500)),
                ('self_option1', models.CharField(max_length=100)),
                ('self_option2', models.CharField(max_length=100)),
                ('self_option3', models.CharField(max_length=100)),
                ('self_option4', models.CharField(max_length=100)),
                ('self_option5', models.CharField(max_length=100)),
                ('self_option6', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Self_development_User_mapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sq_id', models.CharField(max_length=100)),
                ('Suser_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Aptitude_mapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.CharField(max_length=100)),
                ('user_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_feedback', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_Reasoning_mapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('user_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_selfdevelop_mapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfuser_ans', models.CharField(max_length=100)),
                ('self_qid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Verbal_mapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.CharField(max_length=100)),
                ('user_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Verbal',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('q_option_1', models.CharField(max_length=100)),
                ('q_option_2', models.CharField(max_length=100)),
                ('q_option_3', models.CharField(max_length=100)),
                ('q_option_4', models.CharField(max_length=100)),
                ('q_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='about')),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
