# Generated by Django 3.2.7 on 2021-11-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('q_option1', models.CharField(max_length=100)),
                ('q_option2', models.CharField(max_length=100)),
                ('q_option3', models.CharField(max_length=100)),
                ('q_option4', models.CharField(max_length=100)),
                ('q_ans', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reasoning',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=850)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_cresult', models.CharField(max_length=10)),
                ('user_wresult', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_Aptitude_mapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.CharField(max_length=100)),
                ('user_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_feedback', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_Reasoning_mapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('user_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Verbal_mapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.CharField(max_length=100)),
                ('user_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Verbal',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('q_option_1', models.CharField(max_length=100)),
                ('q_option_2', models.CharField(max_length=100)),
                ('q_option_3', models.CharField(max_length=100)),
                ('q_option_4', models.CharField(max_length=100)),
                ('q_answer', models.CharField(max_length=100)),
            ],
        ),
    ]
