# Generated by Django 3.2.7 on 2021-12-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitude',
            name='question',
            field=models.CharField(max_length=900),
        ),
    ]
