# Generated by Django 3.2.10 on 2022-01-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_fetch', models.EmailField(max_length=50)),
            ],
        ),
    ]
