# Generated by Django 3.2.7 on 2022-01-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0002_userresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresult',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
