# Generated by Django 3.2.7 on 2022-01-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0003_alter_userresult_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresult',
            name='userid',
        ),
        migrations.AddField(
            model_name='userresult',
            name='username',
            field=models.CharField(default='Rajat', max_length=100),
            preserve_default=False,
        ),
    ]
