# Generated by Django 3.2.7 on 2021-12-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0003_alter_aptitude_q_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
