# Generated by Django 3.2.7 on 2022-01-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0004_auto_20220105_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_aptitude_mapper',
            old_name='userid',
            new_name='username',
        ),
    ]
