# Generated by Django 3.2.7 on 2022-01-05 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0005_rename_userid_user_aptitude_mapper_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_aptitude_mapper',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
