# Generated by Django 3.2.7 on 2022-01-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0006_alter_user_aptitude_mapper_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_aptitude_mapper',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
