# Generated by Django 3.2.7 on 2022-01-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0008_auto_20220106_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_aptitude_mapper',
            name='testtype',
            field=models.CharField(default='Aptitude', max_length=100),
        ),
    ]
