# Generated by Django 3.2.7 on 2022-01-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0009_user_aptitude_mapper_testtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reasoning_mapper',
            name='testtype',
            field=models.CharField(default='Reasoning', max_length=100),
        ),
    ]
